export class PhysicalRecord {
    constructor(
       public createdBy:string,
       public updatedBy:string,
       public issueDate:string,
       public labReferenceCode:string,
       public dateOfReceipt:string,
       public dateOfTest:string,
       public  cropName:string,
       public  variety:string,
       public seedClass:string,
       public pureSeed:string,
       public weightOfSample:string,
       public inertMatter:string,
       public otherCropSeeds:string,
       public inOfAnalyst:string,
       public cropId:string,
       public seedClassId:string,
       public   update:string,
       public  pureSeedR:string,
       public  weightOfSampleR:string,
       public inertMatterR:string,
       public  otherCropSeedsR:string,
       public  avWtOfSample:string,
       public avWtOfPureSeed:string,
       public avWtOfInert:string,
       public avOtherCrop:string,
       public physicalPurity:string,
       public  otherCropPer:string,
       public  inertPer:string,
       public  weed:string,
       public  weedReplica:string,
       public   weedAverage:string,
       public weedPercentage:string,
       public empId:string,
    
       ){
           
       }
}
